---
title: "Simple document"
output: html_document
---

```{r, echo =FALSE, message=FALSE}
library(tidyverse)
library(janitor)
library(readxl)
library(haven)
```


## import some data

I want to import"FAS_litters.csv".
getwd()

```{r}
litters_df = read_csv("data/FAS_litters.csv")
litters_df
select(litters_df,group)

```

##  `filter`

Let's get rid of rows...
```{r}
filter(litters_df,gd_of_birth == 20)
filter(litters_df,gd0_weight < 20)
filter(litters_df, group =="Con7")
filter(litters_df, pups_survive != 4)
filter(litters_df, !(group == "Con7"))
filter(litters_df, group != "Con7")
filter(litters_df, group =="Con7", gd_of_birth == 20)
filter(litters_df, group %in% c("Con7","Con8"))
filter(litters_df, group =="Con7"| gd_of_birth == 20) ## | == or

drop_na(litters_df, pups_)
```


Let's add or change columns!

```{r}
mutate(litters_df, weight_change = gd18_weight - gd0_weight,
       group = str_to_lower(group))
```


Let's rearrange the data.

```{r}
arrange(litters_df, )
```

## Pipes

```{r}
litters_data_raw= read_csv("data/FAS_litters.csv")
litters_clean_name = janitor :: clean_names(litters_data_raw)
litters_select = select(litters_clean_name, group, pups_survive)
litters_filtered = filter(litters_select, group == "Con7")

litters_df = 
  read_csv("data/FAS_litters.csv") %>%
  janitor :: clean_names() %>%
  select(group, pups_survive) %>%
  filter(group =="Con7")



litters_df = 
  read_csv("data/FAS_litters.csv") %>%
  janitor :: clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    weight_change = gd18_weight - gd0_weight,
    group = str_to_lower(group)
  ) %>%
  drop_na(weight_change)%>%
  filter(group %in% c("con7", "con8"))%>%
  select(litter_number, group, weight_change, everything())
```













# read_csv(/Users)

```{r}
names(litters_df)

litters_df = janitor :: clean_names(litters_df)
names(litters_df)

```

Yay! Now I have better names


```{r}
litters_df

head(litters_df)

```

```{r, eval= FALSE}

view(litters_df)

```


Here's "skimr":

```{r}
skimr :: skim(litters_df)
```



## Arguments in "read_csv"

```{r}

litters_df =
  read_csv(
    "data_wrangling_i/data/FAS_litters.csv",
    skip = 5,
    col_names =FALSE,
    na="Low8"
  )
```


```{r}
litters_data = read_csv(file = "data_wrangling_i/data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
tail(litters_data)



```



## Reading from Excel

```{r}
getwd()
mlb11_df = read_excel("data_wrangling_i/data/mlb11.xlsx")


```



```{r}
fellow_df =  read_excel("data_wrangling_i/data/LotR_Words.xlsx",range = "B3:D6")

```


##  Reading a SAS file

this is where I tried to read a SAS file but did't work
#```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
#```

```{r}
test = read_excel("~/Desktop/best_practice/4th_class_data_wrangling/data_wrangling_i/data/mlb11.xlsx")
```



## navigate to absolute path
```{r}
getwd()
test = read_excel("/Users/jufengxiansheng/Desktop/best_practice/4th_class_data_wrangling/data_wrangling_i/data/mlb11.xlsx")
```

```{r}
library(ggplot2)
plot(cars)
```

```{r}
getwd()
```












